import { Augmentation } from "models/augmentation";
import { NS } from "@ns";

const augTypes: { [name: string]: string[] } = {
  "NeuroFlux Governor": ["Special"],
  "ADR-V1 Pheromone Gene": ["Faction", "Company"],
  "ADR-V2 Pheromone Gene": ["Faction", "Company"],
  "Artificial Bio-neural Network Implant": ["Hacking"],
  "Artificial Synaptic Potentiation": ["Hacking"],
  "SoA - Beauty of Aphrodite": ["Infiltration"],
  "Bionic Arms": ["Combat"],
  "Bionic Legs": ["Combat"],
  "Bionic Spine": ["Combat"],
  "BitWire": ["Hacking"],
  "BLADE-51b Tesla Armor": ["Combat", "Bladeburner"],
  "BLADE-51b Tesla Armor: Power Cells Upgrade": ["Bladeburner"],
  "BLADE-51b Tesla Armor: Energy Shielding Upgrade": ["Combat", "Bladeburner"],
  "BLADE-51b Tesla Armor: Unibeam Upgrade": ["Bladeburner"],
  "BLADE-51b Tesla Armor: Omnibeam Upgrade": ["Bladeburner"],
  "BLADE-51b Tesla Armor: IPU Upgrade": ["Bladeburner"],
  "Blade's Runners": ["Combat", "Bladeburner"],
  "The Blade's Simulacrum": ["Bladeburner"],
  "BrachiBlades": ["Combat"],
  "CRTX42-AA Gene Modification": ["Hacking"],
  "CashRoot Starter Kit": ["Starting"],
  "SoA - Chaos of Dionysus": ["Infiltration"],
  "Combat Rib I": ["Combat"],
  "Combat Rib II": ["Combat"],
  "Combat Rib III": ["Combat"],
  "CordiARC Fusion Reactor": ["Combat"],
  "Cranial Signal Processors - Gen I": ["Hacking"],
  "Cranial Signal Processors - Gen II": ["Hacking"],
  "Cranial Signal Processors - Gen III": ["Hacking"],
  "Cranial Signal Processors - Gen IV": ["Hacking"],
  "Cranial Signal Processors - Gen V": ["Hacking"],
  "DataJack": ["Hacking"],
  "DermaForce Particle Barrier": ["Combat"],
  "EMS-4 Recombination": ["Bladeburner"],
  "Embedded Netburner Module": ["Hacking"],
  "Embedded Netburner Module Core V3 Upgrade": ["Hacking"],
  "Embedded Netburner Module Analyze Engine": ["Hacking"],
  "Embedded Netburner Module Direct Memory Access Upgrade": ["Hacking"],
  "Embedded Netburner Module Core Implant": ["Hacking"],
  "Embedded Netburner Module Core V2 Upgrade": ["Hacking"],
  "Enhanced Myelin Sheathing": ["Hacking"],
  "Enhanced Social Interaction Implant": ["Company"],
  "EsperTech Bladeburner Eyewear": ["Combat", "Bladeburner"],
  "SoA - Flood of Poseidon": ["Infiltration"],
  "FocusWire": ["Combat", "Hacking", "Company"],
  "GOLEM Serum": ["Combat", "Bladeburner"],
  "Graphene Bionic Arms Upgrade": ["Combat"],
  "Graphene Bone Lacings": ["Combat"],
  "Graphene Bionic Spine Upgrade": ["Combat"],
  "Graphene Bionic Legs Upgrade": ["Combat"],
  "Graphene BrachiBlades Upgrade": ["Combat"],
  "Hacknet Node CPU Architecture Neural-Upload": ["Hacknet"],
  "Hacknet Node Cache Architecture Neural-Upload": ["Hacknet"],
  "Hacknet Node NIC Architecture Neural-Upload": ["Hacknet"],
  "Hacknet Node Kernel Direct-Neural Interface": ["Hacknet"],
  "Hacknet Node Core Direct-Neural Interface": ["Hacknet"],
  "HemoRecirculator": ["Combat"],
  "ECorp HVMind Implant": ["Hacking"],
  "SoA - Hunt of Artemis": ["Infiltration"],
  "Hydroflame Left Arm": ["Combat"],
  "Hyperion Plasma Cannon V1": ["Bladeburner"],
  "Hyperion Plasma Cannon V2": ["Bladeburner"],
  "HyperSight Corneal Implant": ["Combat", "Hacking"],
  "INFRARET Enhancement": ["Combat"],
  "I.N.T.E.R.L.I.N.K.E.D": ["Combat", "Bladeburner"],
  "SoA - Knowledge of Apollo": ["Infiltration"],
  "LuminCloaking-V1 Skin Implant": ["Combat"],
  "LuminCloaking-V2 Skin Implant": ["Combat"],
  "SoA - Might of Ares": ["Infiltration"],
  "Nanofiber Weave": ["Combat"],
  "Neotra": ["Combat"],
  "Neural Accelerator": ["Hacking"],
  "Neural-Retention Enhancement": ["Hacking"],
  "Neuralstimulator": ["Hacking"],
  "Neuregen Gene Modification": ["Hacking"],
  "BitRunners Neurolink": ["Hacking"],
  "Neuronal Densification": ["Hacking"],
  "Neuroreceptor Management Implant": ["Company", "Faction"],
  "Neurotrainer I": ["Combat", "Hacking"],
  "Neurotrainer II": ["Combat", "Hacking"],
  "Neurotrainer III": ["Combat", "Hacking"],
  "Nuoptimal Nootropic Injector Implant": ["Company"],
  "NutriGen Implant": ["Combat"],
  "nextSENS Gene Modification": ["Combat", "Company", "Hacking"],
  "OmniTek InfoLoad": ["Hacking"],
  "ORION-MKIV Shoulder": ["Combat", "Bladeburner"],
  "PC Direct-Neural Interface": ["Hacking", "Company"],
  "PC Direct-Neural Interface NeuroNet Injector": ["Company", "Hacking"],
  "PC Direct-Neural Interface Optimization Submodule": ["Company", "Hacking"],
  "PCMatrix": ["Company", "Faction", "Starting"],
  "Photosynthetic Cells": ["Combat"],
  "Power Recirculation Core": ["Hacking", "Combat", "Company"],
  "QLink": ["Hacking"],
  "Synthetic Heart": ["Combat"],
  "Social Negotiation Assistant (S.N.A)": ["Company", "Faction"],
  "SPTN-97 Gene Modification": ["Combat", "Hacking"],
  "The Shadow's Simulacrum": ["Company", "Faction"],
  "SmartJaw": ["Company", "Faction"],
  "SmartSonar Implant": ["Combat"],
  "Speech Enhancement": ["Company"],
  "Speech Processor Implant": ["Company"],
  "Stanek's Gift - Genesis": ["Special"],
  "Stanek's Gift - Awakening": ["Special"],
  "Stanek's Gift - Serenity": ["Special"],
  "NEMEAN Subdermal Weave": ["Combat"],
  "Synaptic Enhancement Implant": ["Hacking"],
  "Synfibril Muscle": ["Combat"],
  "TITN-41 Gene-Modification Injection": ["Company"],
  "Augmented Targeting I": ["Combat"],
  "Augmented Targeting II": ["Combat"],
  "Augmented Targeting III": ["Combat"],
  "The Black Hand": ["Combat", "Hacking"],
  "The Red Pill": ["Special"],
  "SoA - Trickery of Hermes": ["Infiltration"],
  "Unstable Circadian Modulator": ["Special"],
  "Vangelis Virus": ["Combat", "Bladeburner"],
  "Vangelis Virus 3.0": ["Combat", "Bladeburner"],
  "SoA - phyzical WKS harmonizer": ["Infiltration"],
  "Wired Reflexes": ["Combat"],
  "SoA - Wisdom of Athena": ["Infiltration"],
  "Xanipher": ["Hacking", "Combat", "Company"]
}

export async function main(ns: NS) {
  let factions = [
    { name: "Illuminati" },
    { name: "Daedalus" },
    { name: "The Covenant" },
    { name: "ECorp" },
    { name: "MegaCorp" },
    { name: "Bachman & Associates" },
    { name: "Blade Industries" },
    { name: "NWO" },
    { name: "Clarke Incorporated" },
    { name: "OmniTek Incorporated" },
    { name: "Four Sigma" },
    { name: "KuaiGong International" },
    { name: "Fulcrum Secret Technologies" },
    { name: "BitRunners" },
    { name: "The Black Hand" },
    { name: "NiteSec" },
    { name: "Aevum" },
    { name: "Chongqing" },
    { name: "Ishima" },
    { name: "New Tokyo" },
    { name: "Sector-12" },
    { name: "Volhaven" },
    { name: "Speakers for the Dead" },
    { name: "The Dark Army" },
    { name: "The Syndicate" },
    { name: "Silhouette" },
    { name: "Tetrads" },
    { name: "Slum Snakes" },
    { name: "Netburners" },
    { name: "Tian Di Hui" },
    { name: "CyberSec" },
    { name: "Bladeburners" },
    { name: "Church of the Machine God" },
    { name: "Shadows of Anarchy" },
  ];

  let allAugs: Augmentation[] = [];

  for (const faction of factions) {
    const augs = ns.singularity.getAugmentationsFromFaction(faction.name).map(name => new Augmentation(ns, name));
    for (const aug of augs) {
      let processedAug = allAugs.find(a => a.name === aug.name);
      if (processedAug === undefined) {
        processedAug = aug;
        allAugs.push(aug);
        processedAug.types = augTypes[processedAug.name];
      }
      processedAug.factions.push(faction.name);
    }
  }
  ns.write('data/augs.txt', JSON.stringify(allAugs), "w");
}